import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../entities/invoice.dart';

/// Builds a printable PDF representation of an [Invoice] in a layout aimed
/// at the fields Nigeria's e-invoicing format requires: seller/buyer TIN,
/// itemised VAT per line, invoice number and a verification QR code.
class InvoicePdfService {
  const InvoicePdfService();

  Future<pw.Document> build(Invoice invoice) async {
    final doc = pw.Document();
    final dateFmt = (DateTime d) => '${d.day.toString().padLeft(2, '0')}/'
        '${d.month.toString().padLeft(2, '0')}/${d.year}';

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('TAX INVOICE',
                          style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                      pw.Text('Invoice No: ${invoice.invoiceNumber}'),
                      pw.Text('Issue Date: ${dateFmt(invoice.issueDate)}'),
                      pw.Text('Due Date: ${dateFmt(invoice.dueDate)}'),
                      if (invoice.nrsValidationCode != null)
                        pw.Text('Validation Code: ${invoice.nrsValidationCode}'),
                    ],
                  ),
                  pw.BarcodeWidget(
                    data: invoice.invoiceNumber,
                    barcode: pw.Barcode.qrCode(),
                    width: 80,
                    height: 80,
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Expanded(child: _party('Seller', invoice.sellerName, invoice.sellerTin, invoice.sellerAddress)),
                  pw.SizedBox(width: 20),
                  pw.Expanded(child: _party('Buyer', invoice.buyerName, invoice.buyerTin, invoice.buyerAddress)),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
                columnWidths: const {
                  0: pw.FlexColumnWidth(3),
                  1: pw.FlexColumnWidth(1),
                  2: pw.FlexColumnWidth(1.4),
                  3: pw.FlexColumnWidth(1),
                  4: pw.FlexColumnWidth(1.4),
                },
                children: [
                  _headerRow(),
                  ...invoice.items.map(_itemRow),
                ],
              ),
              pw.SizedBox(height: 16),
              pw.Align(
                alignment: pw.Alignment.centerRight,
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.end,
                  children: [
                    _totalLine('Subtotal', invoice.subtotal),
                    _totalLine('Total VAT', invoice.totalVat),
                    pw.Divider(),
                    _totalLine('Grand Total', invoice.grandTotal, bold: true),
                  ],
                ),
              ),
              pw.Spacer(),
              pw.Divider(),
              pw.Text(
                'Generated by E-Invoice NG — formatted for NRS/FIRS e-invoicing '
                'compliance readiness ahead of the July 2027 mandate.',
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
              ),
            ],
          );
        },
      ),
    );
    return doc;
  }

  pw.Widget _party(String label, String name, String tin, String address) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
        pw.Text(name),
        pw.Text('TIN: $tin'),
        pw.Text(address),
      ],
    );
  }

  pw.TableRow _headerRow() {
    pw.Widget cell(String text) => pw.Padding(
          padding: const pw.EdgeInsets.all(4),
          child: pw.Text(text, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9)),
        );
    return pw.TableRow(children: [
      cell('Description'),
      cell('Qty'),
      cell('Unit Price'),
      cell('VAT %'),
      cell('Line Total'),
    ]);
  }

  pw.TableRow _itemRow(InvoiceItem item) {
    pw.Widget cell(String text) => pw.Padding(
          padding: const pw.EdgeInsets.all(4),
          child: pw.Text(text, style: const pw.TextStyle(fontSize: 9)),
        );
    return pw.TableRow(children: [
      cell(item.description),
      cell(item.quantity.toStringAsFixed(0)),
      cell('₦${item.unitPrice.toStringAsFixed(2)}'),
      cell('${(vatRateToPercent(item.vatRate) * 100).toStringAsFixed(1)}%'),
      cell('₦${item.lineTotalWithVat.toStringAsFixed(2)}'),
    ]);
  }

  pw.Widget _totalLine(String label, double value, {bool bold = false}) {
    final style = pw.TextStyle(fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, fontSize: bold ? 13 : 11);
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Text('$label: ₦${value.toStringAsFixed(2)}', style: style),
    );
  }
}
